# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/154SaYRJp-q8GLpeAtWYBrBp57BxuN-qx
"""

print("Hello world!!!")